### PR TITLE
Remove docs part from website.

### PR DESCRIPTION
**Pull request by gabrielmocanu**
Remove docs part from website.

Signed-off-by: Gabriel Mocanu <gabi.mocanu98@gmail.com>

### CODE REVIEW

**Review by teodutu — APPROVED** [review]
It looks legit. But how come you don't have to remove the link to the documentation from the landing page [1]? For the actual tracks, this link must be added manually, but I don't see any reference to it in the landing page's `index.md` file [2].

[1] https://security-summer-school.github.io/docs/
[2] https://github.com/security-summer-school/security-summer-school.github.io/blob/master/content/en/_index.html

**Comment by gabrielmocanu** [comment]
I don't see your point. Those links are for Github and you can see them and the end of the page with `Read more..`.

**Comment by teodutu** [comment]
I mean that in order to add a new track to the bar at the top of the page, one has to link it manually, like so [1]. This doesn't seem to be the case for `/docs/`. Are you sure it isn't linked somewhere else that you forgot to remove and we don't end up with a broken link?

[1] https://github.com/security-summer-school/security-summer-school.github.io/blob/afee713026f232df68ec8903bb835ae258b1d3fb/content/en/_index.html#L46-L48

**Comment by gabrielmocanu** [comment]
Screenshot from 2022-06-24 20-10-16

You don't have to add it manually. The code that you posted is for this bar that you can find in the home page at the end of the scroll.

**Comment by teodutu** [comment]
Interesting. My bad, then. In this case, I think this is good to go.

**Pull request merged**
